### ISSUE TITLE
Viewer for indoor shows

### ISSUE THREAD

**Issue by layorjunia** [skybrush-io/viewer#4]
Add an option to Viewer to make the spheres smaller to accommodate closer takeoff grids and formations for indoor shows. Even having an option to import a obj to take the place of the sphere would be cool, especially for indoor shows since audience members can see the drone itself.

**Comment by ntamas** [comment]
Drone size adjustments were added to the sidebar in version 2.4.0: you can set a scaling factor to adjust the default size (which is already different for outdoor vs indoor shows).
